server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_api
    username: root
    password: atv@@2303
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
